[package]
name = "gne-text-search"
version = "0.1.0"
authors = ["Anthony Drendel <me@anthonydrendel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
